# Generated by Django 4.0 on 2023-02-10 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celery_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='equation',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='message',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='status',
        ),
    ]
