# Generated by Django 4.0 on 2023-02-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_app', '0002_remove_calculation_equation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicTaskCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('task_date_time', models.DateTimeField()),
            ],
        ),
    ]
